import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

export async function POST(request) {
  try {
    const { userId, fullName, email, role } = await request.json();

    // Use service role key for server-side operations (bypasses RLS)
    const supabase = createClient(
      supabaseUrl,
      supabaseServiceKey || supabaseAnonKey
    );

    if (!userId) {
      console.error('User ID is missing in request');
      return NextResponse.json(
        { error: 'User ID is required' },
        { status: 400 }
      );
    }

    // Check if profile already exists (check by id which is the primary key)
    const { data: existingProfile, error: checkError } = await supabase
      .from('profiles')
      .select('id')
      .eq('id', userId)
      .single();

    if (existingProfile) {
      console.log('Profile already exists for user:', userId);
      // Check if public_id is missing and generate it
      const { data: profile, error: fetchError } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userId)
        .single();

      if (fetchError) {
        console.error('Error fetching existing profile:', fetchError);
        return NextResponse.json(
          { error: 'Failed to fetch profile' },
          { status: 500 }
        );
      }

      if (!profile.public_id) {
        // Generate public_id
        let newPublicId;
        let attempts = 0;
        const maxAttempts = 10;

        do {
          newPublicId = Math.random().toString(36).substring(2, 8).toUpperCase();
          attempts++;
          const { data: existing } = await supabase
            .from('profiles')
            .select('id')
            .eq('public_id', newPublicId)
            .single();
          if (existing) continue;
          break;
        } while (attempts < maxAttempts);

        if (attempts >= maxAttempts) {
          newPublicId = (Date.now() % 1000000).toString(36).toUpperCase().padStart(6, '0');
        }

        // Update the profile
        const { data: updatedProfile, error: updateError } = await supabase
          .from('profiles')
          .update({ public_id: newPublicId })
          .eq('id', userId)
          .select()
          .single();

        if (updateError) {
          console.error('Error updating public_id:', updateError);
          // Return profile anyway
          return NextResponse.json({
            success: true,
            profile: profile,
            message: 'Profile exists but public_id update failed'
          });
        }

        return NextResponse.json({
          success: true,
          profile: updatedProfile,
          message: 'Profile updated with public_id'
        });
      }

      return NextResponse.json({
        success: true,
        profile: profile,
        message: 'Profile already exists'
      });
    }

    // public_id will be automatically generated by database trigger
    // No need to generate it manually - the trigger handles uniqueness

    // Validate and set role - ensure correct role is saved
    let validRole = 'recycler'; // Default role
    if (role === 'centre_staff') {
      validRole = 'centre_staff';
      console.log('Setting role to centre_staff for collection centre registration');
    } else if (role === 'recycler') {
      validRole = 'recycler';
      console.log('Setting role to recycler for normal user registration');
    } else {
      console.warn('Invalid role received:', role, '- defaulting to recycler');
      validRole = 'recycler';
    }
    
    // Log the role for debugging
    console.log('Creating profile with role:', validRole, 'for user:', userId, '(received role:', role, ')');

    // Create the profile in Supabase
    // Match the profiles table schema: id, full_name, role, points_total, created_at, public_id
    const profileData = {
      id: userId, // Primary key - user ID from authentication
      full_name: fullName || null,
      role: validRole, // 'centre_staff' or 'recycler'
      points_total: 0, // Initialize points to 0 for new users
      public_id: null, // Let database trigger generate it automatically
      created_at: new Date().toISOString() // Timestamp for when profile was created
    };
    
    console.log('Inserting profile data:', {
      id: profileData.id,
      full_name: profileData.full_name,
      role: profileData.role,
      points_total: profileData.points_total
    });
    
    const { data, error } = await supabase
      .from('profiles')
      .insert([profileData])
      .select()
      .single();

    if (error) {
      console.error('Error creating profile in Supabase:', error);
      console.error('Error details:', {
        code: error.code,
        message: error.message,
        details: error.details,
        hint: error.hint
      });
      
      // Provide more helpful error messages
      let errorMessage = 'Failed to create profile';
      if (error.code === '23505') {
        errorMessage = 'Profile already exists for this user';
      } else if (error.code === '23503') {
        errorMessage = 'Invalid user reference';
      } else if (error.message) {
        errorMessage = `Failed to create profile: ${error.message}`;
      }
      
      return NextResponse.json(
        { 
          error: errorMessage,
          details: error.message,
          code: error.code
        },
        { status: 500 }
      );
    }

    if (!data) {
      console.error('No data returned from profile creation');
      return NextResponse.json(
        { error: 'Profile creation returned no data' },
        { status: 500 }
      );
    }

    // Verify the role was saved correctly in the database
    if (data && data.role) {
      if (data.role !== validRole) {
        console.error('❌ Role mismatch! Expected:', validRole, 'Got:', data.role);
        return NextResponse.json(
          { 
            error: 'Role mismatch in database',
            expected: validRole,
            actual: data.role
          },
          { status: 500 }
        );
      } else {
        console.log('✅ Profile created successfully with correct role:', data.role);
        console.log('   - ID:', data.id || userId);
        console.log('   - Role in profiles table:', data.role);
        console.log('   - Full name:', data.full_name);
        console.log('   - Points total:', data.points_total);
        console.log('   - Public ID:', data.public_id);
        console.log('   - Created at:', data.created_at);
      }
    } else {
      console.error('❌ Profile created but role is missing');
      return NextResponse.json(
        { error: 'Profile created but role is missing' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      profile: data
    });

  } catch (error) {
    console.error('Unexpected error in create-profile:', error);
    console.error('Error stack:', error.stack);
    return NextResponse.json(
      { 
        error: 'Internal server error',
        details: error.message 
      },
      { status: 500 }
    );
  }
}